#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.4 on Fri Dec 27 17:34:23 2019
#

import wx
import GRfgE

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((800, 500))
        self.AnalyzeButton = wx.Button(self, wx.ID_ANY, "Analyze")
        self.ExitButtton = wx.Button(self, wx.ID_ANY, "Exit")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.AnalyzeEvent, self.AnalyzeButton)
        self.Bind(wx.EVT_BUTTON, self.ExitEvent, self.ExitButtton)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("WelcomePage")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add((20, 20), 0, wx.ALL | wx.EXPAND, 0)
        Title = wx.StaticText(self, wx.ID_ANY, "GUI for  tissue extraction of biological sections", style=wx.ALIGN_CENTER)
        Title.SetFont(wx.Font(18, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_1.Add(Title, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL | wx.EXPAND, 30)
        sizer_1.Add((20, 20), 0, wx.ALL | wx.EXPAND, 0)
        Statement = wx.StaticText(self, wx.ID_ANY, "\tThe GUI was developed based on Python 3.x, MIT License. It helps handling with Microscopic images, and is mainly supposed to be used for tissue extraction of plant sections.")
        Statement.SetFont(wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_1.Add(Statement, 2, wx.ALIGN_CENTER_HORIZONTAL | wx.EXPAND | wx.LEFT | wx.RIGHT, 60)
        sizer_1.Add((20, 19), 0, wx.ALL | wx.EXPAND, 0)
        sizer_2.Add(self.AnalyzeButton, 0, wx.ALL, 2)
        sizer_2.Add((50, 20), 1, wx.ALL, 0)
        sizer_2.Add(self.ExitButtton, 1, wx.ALL, 2)
        sizer_1.Add(sizer_2, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 5)
        Signature = wx.StaticText(self, wx.ID_ANY, "The Laboratory of Biomass & Bioprocessing Engineering\nCollege of Engineering, China Agricultural University", style=wx.ALIGN_CENTER)
        sizer_1.Add(Signature, 1, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 15)
        self.SetSizer(sizer_1)
        self.Layout()
        self.Centre()
        # end wxGlade

    def AnalyzeEvent(self, event):  # wxGlade: MyFrame.<event_handler>
        #print("Event handler 'AnalyzeEvent' not implemented!")
        #event.Skip()

        self.frame = GRfgE.MyFrame(None, wx.ID_ANY, "")
        self.frame.setParent(self)
        self.Hide()
        self.frame.Show()
        self.frame.Center()
        # 进行一次缩放，各控件(尤其是Canvas)完整显示
        self.frame.SetSize((1920, 1080))
        self.frame.SetSize((1100, 800))
        return True

    def ExitEvent(self, event):  # wxGlade: MyFrame.<event_handler>
        #print("Event handler 'ExitEvent' not implemented!")
        #event.Skip()

        self.Destroy()

# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
